# Generated by Django 3.1.7 on 2021-09-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('public_key', models.CharField(max_length=120)),
                ('private_key', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
